// src/lib/components/Header.svelte
<!-- src/lib/components/Header.svelte -->
<script lang="ts">
  export let siteTitle: string;
  export let subtitle: string;
</script>

<header class="w-full max-w-2xl mx-auto px-4 pt-12 pb-6">
  <h1 class="text-2xl font-semibold tracking-tight" style="color:var(--color-text)">
    {siteTitle}
  </h1>
  {#if subtitle}
    <p class="mt-1 text-sm" style="color:var(--color-muted)">{subtitle}</p>
  {/if}
</header>

// src/components/Header.tsx
import ThemeToggle from "./ThemeToggle";

const siteTitle = process.env.LATELY_SITE_TITLE ?? "Lately";
const subtitle = process.env.LATELY_SUBTITLE ?? "";

export default function Header() {
  return (
    <header className="border-b border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
      <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3">
        <div>
          <span className="text-lg font-semibold tracking-tight text-zinc-900 dark:text-zinc-50">
            {siteTitle}
          </span>
          {subtitle && (
            <span className="ml-2 text-sm text-zinc-500 dark:text-zinc-400">
              {subtitle}
            </span>
          )}
        </div>
        <ThemeToggle />
      </div>
    </header>
  );
}
