// src/components/add-steps/MetadataPreview.tsx
'use client';

import type { Post } from '@/lib/types/post';
import PostCard from '@/components/PostCard';

interface MetadataPreviewProps {
  post: Omit<Post, 'id' | 'user_id' | 'created_at'> & { created_at?: string };
  onConfirm: () => void;
  onBack: () => void;
}

export default function MetadataPreview({ post, onConfirm, onBack }: MetadataPreviewProps) {
  const previewPost: Post = {
    ...post,
    id: 'preview',
    user_id: 'preview',
    created_at: post.created_at ?? new Date().toISOString(),
    caption: post.caption ?? null,
  };

  return (
    <div className="space-y-4">
      <p className="text-xs text-neutral-500 dark:text-neutral-400">Preview</p>
      <PostCard post={previewPost} />
      <div className="flex gap-2">
        <button
          onClick={onBack}
          className="flex-1 py-2 text-sm border border-neutral-200 dark:border-neutral-700 rounded-lg text-neutral-600 dark:text-neutral-400 hover:border-neutral-400 dark:hover:border-neutral-500 transition-colors"
        >
          Back
        </button>
        <button
          onClick={onConfirm}
          className="flex-1 py-2 text-sm font-medium rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 hover:opacity-90 transition-opacity"
        >
          Looks good
        </button>
      </div>
    </div>
  );
}

// src/lib/components/add-steps/MetadataPreview.svelte
<script lang="ts">
  import type { PostType, PostData } from '$lib/types/post';
  import PostCard from '$lib/components/PostCard.svelte';
  import { createEventDispatcher } from 'svelte';

  export let type: PostType;
  export let data: PostData;
  const dispatch = createEventDispatcher<{ confirm: void; back: void }>();

  // Synthesise a fake post for preview
  $: previewPost = {
    id: 'preview',
    user_id: '',
    type,
    caption: null,
    is_private: false,
    created_at: new Date().toISOString(),
    data
  };
</script>

<div>
  <p class="text-sm mb-3" style="color:var(--color-muted)">Looks right?</p>
  <PostCard post={previewPost} isOwner={false} username="" />
  <div class="flex gap-2 mt-4">
    <button
      on:click={() => dispatch('back')}
      class="px-4 py-2 rounded text-sm border"
      style="border-color:var(--color-border);color:var(--color-text)"
    >
      Back
    </button>
    <button
      on:click={() => dispatch('confirm')}
      class="px-4 py-2 rounded text-sm font-medium"
      style="background:var(--color-accent);color:var(--color-bg)"
    >
      Confirm
    </button>
  </div>
</div>
