// src/components/Footer.tsx
const socialLinksRaw = process.env.LATELY_SOCIAL_LINKS ?? "";

type SocialLink = { label: string; url: string };

function parseSocialLinks(raw: string): SocialLink[] {
  if (!raw) return [];
  return raw
    .split(",")
    .map((entry) => {
      const [label, url] = entry.split("|").map((s) => s.trim());
      return label && url ? { label, url } : null;
    })
    .filter((x): x is SocialLink => x !== null);
}

const socialLinks = parseSocialLinks(socialLinksRaw);

export default function Footer() {
  return (
    <footer className="mt-auto border-t border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
      <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3 text-sm text-zinc-500 dark:text-zinc-400">
        <span>&copy; {new Date().getFullYear()}</span>
        {socialLinks.length > 0 && (
          <nav aria-label="Social links" className="flex gap-4">
            {socialLinks.map(({ label, url }) => (
              <a
                key={url}
                href={url}
                className="hover:text-zinc-900 dark:hover:text-zinc-50"
                target="_blank"
                rel="noopener noreferrer"
              >
                {label}
              </a>
            ))}
          </nav>
        )}
      </div>
    </footer>
  );
}

// src/lib/components/Footer.svelte
<!-- src/lib/components/Footer.svelte -->
<script lang="ts">
  export let username: string;
  export let socialLinks: Array<{ label: string; url: string }> = [];
</script>

<footer class="w-full max-w-2xl mx-auto px-4 py-8 mt-12 border-t" style="border-color:var(--color-border)">
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 text-sm" style="color:var(--color-muted)">
    <span>&copy; {new Date().getFullYear()} {username}</span>
    {#if socialLinks.length}
      <div class="flex gap-4">
        {#each socialLinks as link}
          <a href={link.url} target="_blank" rel="noopener noreferrer" style="color:var(--color-muted)" class="hover:underline">
            {link.label}
          </a>
        {/each}
      </div>
    {/if}
  </div>
</footer>
