// src/components/PostCard.tsx
import type { Post } from '@/lib/types/post';
import type { MusicData, VideoData, MovieData, TvData, BookData, QuoteData, PhotoData, LinkData, PodcastData, SocialData } from '@/lib/types/post';
import PostIcon from './PostIcon';
import { getPostLabel } from '@/lib/utils/labels';
import { formatPostDate } from '@/lib/utils/date';
import MusicCard from './post-types/MusicCard';
import VideoCard from './post-types/VideoCard';
import MovieCard from './post-types/MovieCard';
import TvCard from './post-types/TvCard';
import BookCard from './post-types/BookCard';
import QuoteCard from './post-types/QuoteCard';
import PhotoCard from './post-types/PhotoCard';
import LinkCard from './post-types/LinkCard';
import PodcastCard from './post-types/PodcastCard';
import SocialCard from './post-types/SocialCard';

interface PostCardProps {
  post: Post;
  isOwner?: boolean;
  onEdit?: (post: Post) => void;
  onDelete?: (id: string) => void;
}

function PostContent({ post }: { post: Post }) {
  switch (post.type) {
    case 'music':  return <MusicCard data={post.data as MusicData} />;
    case 'video':  return <VideoCard data={post.data as VideoData} />;
    case 'movie':  return <MovieCard data={post.data as MovieData} />;
    case 'tv':     return <TvCard data={post.data as TvData} />;
    case 'book':   return <BookCard data={post.data as BookData} />;
    case 'quote':  return <QuoteCard data={post.data as QuoteData} />;
    case 'photo':  return <PhotoCard data={post.data as PhotoData} />;
    case 'link':   return <LinkCard data={post.data as LinkData} />;
    case 'podcast':return <PodcastCard data={post.data as PodcastData} />;
    case 'social': return <SocialCard data={post.data as SocialData} />;
  }
}

export default function PostCard({ post, isOwner, onEdit, onDelete }: PostCardProps) {
  return (
    <article className="border border-neutral-100 dark:border-neutral-800 rounded-xl p-4 group">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-1.5 text-xs text-neutral-400 dark:text-neutral-500">
          <PostIcon type={post.type} className="w-3.5 h-3.5" />
          <span>{getPostLabel(post.type)}</span>
        </div>
        <div className="flex items-center gap-3">
          <time className="text-xs text-neutral-400 dark:text-neutral-500">
            {formatPostDate(post.created_at)}
          </time>
          {isOwner && (
            <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <button
                onClick={() => onEdit?.(post)}
                className="text-xs text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-300"
              >
                Edit
              </button>
              <button
                onClick={() => onDelete?.(post.id)}
                className="text-xs text-neutral-400 hover:text-red-500"
              >
                Delete
              </button>
            </div>
          )}
        </div>
      </div>

      <PostContent post={post} />

      {post.caption && (
        <p className="mt-3 text-sm text-neutral-600 dark:text-neutral-400">
          {post.caption}
        </p>
      )}
    </article>
  );
}

// src/lib/components/PostCard.svelte
<!-- src/lib/components/PostCard.svelte -->
<script lang="ts">
  import type { Post } from '$lib/types/post';
  import { getPostLabel } from '$lib/utils/labels';
  import { formatPostDate, formatPostTime } from '$lib/utils/date';
  import BookCard from './post-types/BookCard.svelte';
  import TvCard from './post-types/TvCard.svelte';
  import MovieCard from './post-types/MovieCard.svelte';
  import TweetCard from './post-types/TweetCard.svelte';
  import GifCard from './post-types/GifCard.svelte';
  import PhotoCard from './post-types/PhotoCard.svelte';
  import MusicCard from './post-types/MusicCard.svelte';
  import VideoCard from './post-types/VideoCard.svelte';

  export let post: Post;
  export let isOwner: boolean = false;
  export let username: string = '';

  const components = {
    book: BookCard,
    tv: TvCard,
    movie: MovieCard,
    tweet: TweetCard,
    gif: GifCard,
    photo: PhotoCard,
    music: MusicCard,
    video: VideoCard
  };

  $: component = components[post.type];
  $: label = getPostLabel(post.type);

  async function togglePrivate() {
    await fetch('/api/posts', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id: post.id, is_private: !post.is_private })
    });
    window.location.reload();
  }

  async function deletePost() {
    if (!confirm('Delete this post?')) return;
    await fetch('/api/posts', {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id: post.id })
    });
    window.location.reload();
  }
</script>

<article class="py-6 border-b" style="border-color:var(--color-border)">
  <div class="flex items-center justify-between mb-3">
    <span class="text-xs font-medium uppercase tracking-wider" style="color:var(--color-muted)">
      {label}
      {#if post.is_private}
        <span class="ml-1 opacity-50">(private)</span>
      {/if}
    </span>
    <div class="flex items-center gap-3">
      <a
        href="/{username}/{post.id}"
        class="text-xs"
        style="color:var(--color-muted)"
        title="{formatPostDate(post.created_at)} at {formatPostTime(post.created_at)}"
      >
        {formatPostDate(post.created_at)}
      </a>
      {#if isOwner}
        <button on:click={togglePrivate} class="text-xs" style="color:var(--color-muted)" title={post.is_private ? 'Make public' : 'Make private'}>
          {post.is_private ? '👁' : '🔒'}
        </button>
        <button on:click={deletePost} class="text-xs" style="color:var(--color-muted)" title="Delete post">
          ✕
        </button>
      {/if}
    </div>
  </div>

  <svelte:component this={component} data={post.data} />

  {#if post.caption}
    <p class="mt-3 text-sm leading-relaxed" style="color:var(--color-text)">{post.caption}</p>
  {/if}
</article>
